spring:
  data:
    mongodb:
      uri : mongodb+srv://<username>:<password>@******.oflwqac.mongodb.net/?retryWrites=true&w=majority
      database : Task
      host: hostIpOnWhichMongoIsRunning
      port : 27017
